"""catalogo, pre-requisito externo e grafo de dependencias

Revision ID: 1913c658c4eb
Revises: 7ccea5018696
Create Date: 2026-07-15 23:13:42.769427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1913c658c4eb'
down_revision: Union[str, None] = '7ccea5018696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_migracao_template_dependencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_migracao_template_id', sa.Integer(), nullable=False),
    sa.Column('depende_de_template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depende_de_template_id'], ['template.id'], name=op.f('fk_tipo_migracao_template_dependencia_depende_de_template_id_template')),
    sa.ForeignKeyConstraint(['tipo_migracao_template_id'], ['tipo_migracao_template.id'], name=op.f('fk_tipo_migracao_template_dependencia_tipo_migracao_template_id_tipo_migracao_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tipo_migracao_template_dependencia'))
    )
    op.create_index(op.f('ix_tipo_migracao_template_dependencia_depende_de_template_id'), 'tipo_migracao_template_dependencia', ['depende_de_template_id'], unique=False)
    op.create_index(op.f('ix_tipo_migracao_template_dependencia_tipo_migracao_template_id'), 'tipo_migracao_template_dependencia', ['tipo_migracao_template_id'], unique=False)
    # server_default garante que os templates ja existentes (Agencias, Estrutura, Ocupacao,
    # Escala) recebam eh_catalogo=false em vez de violar NOT NULL.
    op.add_column('template', sa.Column('eh_catalogo', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('template', sa.Column('pre_requisito_externo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'pre_requisito_externo')
    op.drop_column('template', 'eh_catalogo')
    op.drop_index(op.f('ix_tipo_migracao_template_dependencia_tipo_migracao_template_id'), table_name='tipo_migracao_template_dependencia')
    op.drop_index(op.f('ix_tipo_migracao_template_dependencia_depende_de_template_id'), table_name='tipo_migracao_template_dependencia')
    op.drop_table('tipo_migracao_template_dependencia')
    # ### end Alembic commands ###
