"""xml registro xpath em template

Revision ID: 93d7c22f0d66
Revises: ee2308918335
Create Date: 2026-07-16 16:11:11.334633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d7c22f0d66'
down_revision: Union[str, None] = 'ee2308918335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('xml_registro_xpath', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'xml_registro_xpath')
    # ### end Alembic commands ###
