"""pk sequencial, blocos condicionais e novocodigo

Revision ID: 9c32e9ab80e3
Revises: e3ba1be9ec34
Create Date: 2026-07-15 20:45:26.446529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c32e9ab80e3'
down_revision: Union[str, None] = 'e3ba1be9ec34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novocodigo',
    sa.Column('nr_org', sa.Integer(), nullable=False),
    sa.Column('cd_contador', sa.String(length=100), nullable=False),
    sa.Column('nr_proximo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nr_org', 'cd_contador', name=op.f('pk_novocodigo'))
    )
    op.add_column('template_campo', sa.Column('gerador_pk_contador', sa.String(length=100), nullable=True))
    op.add_column('template_campo', sa.Column('gerador_pk_seed', sa.Integer(), nullable=True))
    # server_default garante que o único registro já existente (o script de Agências
    # Bancárias, semeado na Fase 2) receba ordem=1 em vez de violar NOT NULL.
    op.add_column('template_script', sa.Column('ordem', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('template_script', sa.Column('condicao_campo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_script', 'condicao_campo')
    op.drop_column('template_script', 'ordem')
    op.drop_column('template_campo', 'gerador_pk_seed')
    op.drop_column('template_campo', 'gerador_pk_contador')
    op.drop_table('novocodigo')
    # ### end Alembic commands ###
