"""organizacao, migracao e staging persistido

Revision ID: b7f4f3205980
Revises: dc048688bf05
Create Date: 2026-07-16 10:07:19.070672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7f4f3205980'
down_revision: Union[str, None] = 'dc048688bf05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacao',
    sa.Column('nr_org', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('nr_org', name=op.f('pk_organizacao'))
    )
    op.create_table('migracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nr_org', sa.Integer(), nullable=False),
    sa.Column('tipo_migracao_id', sa.Integer(), nullable=False),
    sa.Column('operador', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('dt_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nr_org'], ['organizacao.nr_org'], name=op.f('fk_migracao_nr_org_organizacao')),
    sa.ForeignKeyConstraint(['tipo_migracao_id'], ['tipo_migracao.id'], name=op.f('fk_migracao_tipo_migracao_id_tipo_migracao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migracao'))
    )
    op.create_index(op.f('ix_migracao_nr_org'), 'migracao', ['nr_org'], unique=False)
    op.create_index(op.f('ix_migracao_tipo_migracao_id'), 'migracao', ['tipo_migracao_id'], unique=False)
    op.create_table('migracao_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migracao_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.String(length=300), nullable=False),
    sa.Column('usuario', sa.String(length=200), nullable=False),
    sa.Column('dt_evento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['migracao_id'], ['migracao.id'], name=op.f('fk_migracao_evento_migracao_id_migracao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migracao_evento'))
    )
    op.create_index(op.f('ix_migracao_evento_migracao_id'), 'migracao_evento', ['migracao_id'], unique=False)
    op.create_table('migracao_template_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migracao_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('arquivo_origem', sa.String(length=300), nullable=True),
    sa.Column('hash_arquivo', sa.String(length=64), nullable=True),
    sa.Column('total_linhas', sa.Integer(), nullable=False),
    sa.Column('linhas_processadas', sa.Integer(), nullable=False),
    sa.Column('pausado', sa.Boolean(), nullable=False),
    sa.Column('teve_alerta', sa.Boolean(), nullable=False),
    sa.Column('dados_aprovados', sa.Boolean(), nullable=False),
    sa.Column('aprovado_dados_por', sa.String(length=200), nullable=True),
    sa.Column('script_gerado', sa.Boolean(), nullable=False),
    sa.Column('script_aprovado', sa.Boolean(), nullable=False),
    sa.Column('aprovado_script_por', sa.String(length=200), nullable=True),
    sa.Column('aplicado', sa.Boolean(), nullable=False),
    sa.Column('aplicado_com_erro', sa.Boolean(), nullable=False),
    sa.Column('dt_importacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['migracao_id'], ['migracao.id'], name=op.f('fk_migracao_template_status_migracao_id_migracao')),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], name=op.f('fk_migracao_template_status_template_id_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migracao_template_status'))
    )
    op.create_index(op.f('ix_migracao_template_status_migracao_id'), 'migracao_template_status', ['migracao_id'], unique=False)
    op.create_index(op.f('ix_migracao_template_status_template_id'), 'migracao_template_status', ['template_id'], unique=False)
    op.create_table('script_gerado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migracao_template_status_id', sa.Integer(), nullable=False),
    sa.Column('operacao', sa.String(length=20), nullable=False),
    sa.Column('conteudo_sql', sa.Text(), nullable=False),
    sa.Column('dt_geracao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['migracao_template_status_id'], ['migracao_template_status.id'], name=op.f('fk_script_gerado_migracao_template_status_id_migracao_template_status'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_gerado'))
    )
    op.create_index(op.f('ix_script_gerado_migracao_template_status_id'), 'script_gerado', ['migracao_template_status_id'], unique=False)
    op.create_table('staging_bruto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migracao_template_status_id', sa.Integer(), nullable=False),
    sa.Column('linha', sa.Integer(), nullable=False),
    sa.Column('dados_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['migracao_template_status_id'], ['migracao_template_status.id'], name=op.f('fk_staging_bruto_migracao_template_status_id_migracao_template_status'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staging_bruto'))
    )
    op.create_index(op.f('ix_staging_bruto_migracao_template_status_id'), 'staging_bruto', ['migracao_template_status_id'], unique=False)
    op.create_table('staging_normalizado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staging_bruto_id', sa.Integer(), nullable=False),
    sa.Column('dados_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dt_processamento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staging_bruto_id'], ['staging_bruto.id'], name=op.f('fk_staging_normalizado_staging_bruto_id_staging_bruto'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staging_normalizado'))
    )
    op.create_index(op.f('ix_staging_normalizado_staging_bruto_id'), 'staging_normalizado', ['staging_bruto_id'], unique=True)
    op.create_table('validacao_resultado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staging_normalizado_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=False),
    sa.Column('regra', sa.String(length=100), nullable=False),
    sa.Column('classificacao', sa.String(length=30), nullable=False),
    sa.Column('valor_recebido', sa.Text(), nullable=False),
    sa.Column('valor_esperado', sa.Text(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['staging_normalizado_id'], ['staging_normalizado.id'], name=op.f('fk_validacao_resultado_staging_normalizado_id_staging_normalizado'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validacao_resultado'))
    )
    op.create_index(op.f('ix_validacao_resultado_staging_normalizado_id'), 'validacao_resultado', ['staging_normalizado_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validacao_resultado_staging_normalizado_id'), table_name='validacao_resultado')
    op.drop_table('validacao_resultado')
    op.drop_index(op.f('ix_staging_normalizado_staging_bruto_id'), table_name='staging_normalizado')
    op.drop_table('staging_normalizado')
    op.drop_index(op.f('ix_staging_bruto_migracao_template_status_id'), table_name='staging_bruto')
    op.drop_table('staging_bruto')
    op.drop_index(op.f('ix_script_gerado_migracao_template_status_id'), table_name='script_gerado')
    op.drop_table('script_gerado')
    op.drop_index(op.f('ix_migracao_template_status_template_id'), table_name='migracao_template_status')
    op.drop_index(op.f('ix_migracao_template_status_migracao_id'), table_name='migracao_template_status')
    op.drop_table('migracao_template_status')
    op.drop_index(op.f('ix_migracao_evento_migracao_id'), table_name='migracao_evento')
    op.drop_table('migracao_evento')
    op.drop_index(op.f('ix_migracao_tipo_migracao_id'), table_name='migracao')
    op.drop_index(op.f('ix_migracao_nr_org'), table_name='migracao')
    op.drop_table('migracao')
    op.drop_table('organizacao')
    # ### end Alembic commands ###
