"""template e tipo_migracao

Revision ID: bd07a3970c79
Revises: c01c65ae22f5
Create Date: 2026-07-15 20:08:58.306975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd07a3970c79'
down_revision: Union[str, None] = 'c01c65ae22f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('versao', sa.String(length=20), nullable=False),
    sa.Column('formatos_aceitos', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('header_row', sa.Integer(), nullable=True),
    sa.Column('data_start_row', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template'))
    )
    op.create_index(op.f('ix_template_codigo'), 'template', ['codigo'], unique=True)
    op.create_table('tipo_migracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('banco_destino', sa.String(length=20), nullable=False),
    sa.Column('permite_concorrencia', sa.Boolean(), nullable=False),
    sa.Column('modo_aplicacao', sa.String(length=20), nullable=False),
    sa.Column('sequencia_obrigatoria', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tipo_migracao'))
    )
    op.create_index(op.f('ix_tipo_migracao_codigo'), 'tipo_migracao', ['codigo'], unique=True)
    op.create_table('template_campo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=100), nullable=False),
    sa.Column('rotulo', sa.String(length=200), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=False),
    sa.Column('marcador', sa.String(length=100), nullable=True),
    sa.Column('destino_tabela', sa.String(length=100), nullable=False),
    sa.Column('destino_coluna', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('tamanho_maximo', sa.Integer(), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('valor_padrao', sa.String(length=200), nullable=True),
    sa.Column('regra_conversao', sa.String(length=50), nullable=True),
    sa.Column('regra_validacao', sa.Text(), nullable=True),
    sa.Column('eh_pk', sa.Boolean(), nullable=False),
    sa.Column('gerador_pk', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], name=op.f('fk_template_campo_template_id_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_campo'))
    )
    op.create_index(op.f('ix_template_campo_template_id'), 'template_campo', ['template_id'], unique=False)
    op.create_table('template_script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('operacao', sa.String(length=20), nullable=False),
    sa.Column('dialeto_banco', sa.String(length=20), nullable=False),
    sa.Column('template_sql', sa.Text(), nullable=False),
    sa.Column('template_rollback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], name=op.f('fk_template_script_template_id_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_script'))
    )
    op.create_index(op.f('ix_template_script_template_id'), 'template_script', ['template_id'], unique=False)
    op.create_table('tipo_migracao_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_migracao_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], name=op.f('fk_tipo_migracao_template_template_id_template')),
    sa.ForeignKeyConstraint(['tipo_migracao_id'], ['tipo_migracao.id'], name=op.f('fk_tipo_migracao_template_tipo_migracao_id_tipo_migracao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tipo_migracao_template'))
    )
    op.create_index(op.f('ix_tipo_migracao_template_template_id'), 'tipo_migracao_template', ['template_id'], unique=False)
    op.create_index(op.f('ix_tipo_migracao_template_tipo_migracao_id'), 'tipo_migracao_template', ['tipo_migracao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipo_migracao_template_tipo_migracao_id'), table_name='tipo_migracao_template')
    op.drop_index(op.f('ix_tipo_migracao_template_template_id'), table_name='tipo_migracao_template')
    op.drop_table('tipo_migracao_template')
    op.drop_index(op.f('ix_template_script_template_id'), table_name='template_script')
    op.drop_table('template_script')
    op.drop_index(op.f('ix_template_campo_template_id'), table_name='template_campo')
    op.drop_table('template_campo')
    op.drop_index(op.f('ix_tipo_migracao_codigo'), table_name='tipo_migracao')
    op.drop_table('tipo_migracao')
    op.drop_index(op.f('ix_template_codigo'), table_name='template')
    op.drop_table('template')
    # ### end Alembic commands ###
