"""usuario e rbac

Revision ID: ee2308918335
Revises: 23bd8d788a9b
Create Date: 2026-07-16 12:20:08.857152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2308918335'
down_revision: Union[str, None] = '23bd8d788a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=200), nullable=True),
    sa.Column('papel', sa.String(length=30), nullable=False),
    sa.Column('nr_org', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('dt_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nr_org'], ['organizacao.nr_org'], name=op.f('fk_usuario_nr_org_organizacao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario'))
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_nr_org'), 'usuario', ['nr_org'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_nr_org'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
